spring:
  application:
    name: High-Concurrency Ticket System
  profiles:
    active:
  datasource:
    hikari:
      maximum-pool-size: 50
    url: jdbc:sqlserver://localhost:1433;databaseName=ticketdb;trustServerCertificate=true
    username: sa
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
jwt:
  secretKey: YciddydL3yrPZPBsf+0gqx5EL80dKL9MyMImRR7Jp3A3Is70nvEbQtgCm2nytMTItZexrgJZPysYfeJ7SdLuqw==
server:
  tomcat:
    threads:
      max: 200